language: node_js
node_js:
  - '0.10'
after_script:
  - npm install -g codeclimate-test-reporter
  - CODECLIMATE_REPO_TOKEN=dc32cda33fccab11b4851b30ee63f08e2b9d31249fbd1a42d233bf79d5c7643a codeclimate-test-reporter < ./coverage/lcov.info
